### ISSUE TITLE
社区签到功能失效

### ISSUE THREAD

**Issue by abbaccadd0** [Womsxd/AutoMihoyoBBS#299]
例如，在config中配置
```
mihoyobbs:

  enable: true

  checkin: true

  checkin_multi: true

  checkin_multi_list:

    - 6

    - 8
```
直接运行后提示`今天已经全部完成了！`

但实际上

![IMG_5436(20221102-142905)](https://user-images.githubusercontent.com/39579855/199414545-90bb0f7f-4b7a-4726-b821-1c1bf0eac061.PNG)
